### ISSUE TITLE
ggdid and aggte

### ISSUE THREAD

**Issue by ealda** [NickCH-K/did#11]
The package works great with att_gt but, for the life of me, I can't  figure out how to run aggte and ggdid commands in stata. Does one have to store the estimates before running ggdid? 

Thanks again for putting this resource out for stata users
Best

**Comment by NickCH-K** [comment]
There's a very good reason for that, which is that those functions don't exist yet :P The package is still in development, and `att_gt` is currently the only working function. I just today started work on `aggte`.

For now, after you run `att_gt` you should I think be able to see the results of `aggte` by doing:

```
rcall: print(summary(aggte(CS_Model)))
```

**Comment by ealda** [comment]
Oh, Duh!. Thanks for the quick response. It works great Nick!!

**Comment by NickCH-K** [comment]
You're welcome!
