### ISSUE TITLE
error in option control_group()

### ISSUE THREAD

**Issue by Hveemos** [NickCH-K/did#12]
`att_gt lemp year firsttreat lpop, idname(countyreal) control_group("nevertreated")`
returns the following error:
```
variable nevertreated not found
(error in option control_group())
 ```

I checked the ado-files _att_gt.ado_ and _att_gt_helper.ado_  and saw this chunk:

syntax varlist(min=3) [if] [in] [iweight], ///
		[clearR panel_no idname(varname) xformla(string) allow_unbalanced_panel **control_group(varlist)** ///
		anticipation(integer 0) ALPha(real 0.05) bootstrap_no cband_no biters(integer 1000) ///
		CLUStervars(varlist max=2) est_method(string) pl cores(integer 1)]
	marksample touse

 So I changed **control_group(varlist)** to **control_group(string)** in both ado-files. Now the code runs without error.

**Comment by NickCH-K** [comment]
Fixed, thank you
