### ISSUE TITLE
"read rcall helpfile"

### ISSUE THREAD

**Issue by Danferno** [NickCH-K/did#2]
> If the installation fails, read the rcall help file and install 
> the dependencies manually.

Clarify that you mean the Stata help file. You can add a clickable link. 
```
di "{help rcall}"
```

I did not find any info in the rcall help file on how to manually install the dependencies

**Comment by Danferno** [comment]
In my case the issue was that I did not have write permission in the R folder

**Comment by NickCH-K** [comment]
Good timing - just now working on this. The next push will have some additional details.

**Comment by NickCH-K** [comment]
Fixed with f4e2467
