### ISSUE TITLE
.cmd hangs on installing dependencies

### ISSUE THREAD

**Issue by Danferno** [NickCH-K/did#4]
![afbeelding](https://user-images.githubusercontent.com/20988490/113677787-3e69b600-96be-11eb-93f9-a97e4896fdaf.png)
There's a flashing underscore but nothing seems to be happening?

**Comment by Danferno** [comment]
I closed the window and now I get a lot of empty .cmd windows opening, sometimes they show here() starts at C:/StataWD

**Comment by Danferno** [comment]
I think maybe it was installing the packages but didn't flush text to the cmd window? At least something similar happened when I installed in R directly and then more output appeared when I clicked in the window. Maybe add a warning that this can take a while?

**Comment by NickCH-K** [comment]
The empty .cmd windows are `rcall` doing its thing. It likes to open and close a lot of .cmd windows. Those are the flashing lights I warn about in documentation.

The hang is a bit concerning. Just happen to be working now on documentation updates about this.

**Comment by Danferno** [comment]
Would there be a way of just running an R-script once instead of the separate calls? Or are you dependent on Rcall for that? (I'm not an R user)

**Comment by NickCH-K** [comment]
It produces a lot of .cmd windows even with only one `rcall` call. I've done some things to slim down the number you get in most parts of the package. Although in the case of `didsetup` the checks for package installation need to be their own calls, so that increases things a bit.

**Comment by NickCH-K** [comment]
Fixed (to the extent possible) with f4e2467
