### ISSUE TITLE
mpdta complains about data in memory

### ISSUE THREAD

**Issue by Danferno** [NickCH-K/did#5]
A clear before mpdta does not fix the issue
![afbeelding](https://user-images.githubusercontent.com/20988490/113679288-e764e080-96bf-11eb-83a8-f5a738840f17.png)

It seems to be creating an empty column at some point, maybe that's the issue?
![afbeelding](https://user-images.githubusercontent.com/20988490/113679412-06fc0900-96c0-11eb-98fa-c8bb06cd234f.png)

**Comment by Danferno** [comment]
It works if you delete the ```set obs 2500``` line from mpdta

![afbeelding](https://user-images.githubusercontent.com/20988490/113679702-5a6e5700-96c0-11eb-9bb0-7c49d911fe13.png)

**Comment by NickCH-K** [comment]
Fixed with f4e2467
