### ISSUE TITLE
did package missing, but is not missing

### ISSUE THREAD

**Issue by Danferno** [NickCH-K/did#6]
![afbeelding](https://user-images.githubusercontent.com/20988490/113680220-e3858e00-96c0-11eb-82dd-125443612281.png)

However, did was installed successfully. I did spot some error message in the .cmd window on a broom package before it disappeared. Manually installing that one in R did seem to help.

![afbeelding](https://user-images.githubusercontent.com/20988490/113680452-247da280-96c1-11eb-927b-fd3a65a4d5c7.png)

**Comment by Danferno** [comment]
Weirdly enough, it still seems to complain about broom

![afbeelding](https://user-images.githubusercontent.com/20988490/113680718-732b3c80-96c1-11eb-964c-7871ff5b2be1.png)

**Comment by NickCH-K** [comment]
Good to know. For some reason `rcall: install.packages(dependencies = TRUE)` is iffy on its willingness to actually install dependencies. I'll add **broom** to the list.

It's possible that it's still complaining about **broom** if `rcall` and your actual R installation are targeting different library folders. Try `rcall: install.packages('broom')` and see if it still has a problem.

**Comment by NickCH-K** [comment]
It's also possible that the error is just hanging around because `rcall` sometimes has a hard time forgetting old errors. If `rcall: install.packages('broom')` still doesn't do it, you might try restarting Stata.

**Comment by Danferno** [comment]
It might be the latter. 

![afbeelding](https://user-images.githubusercontent.com/20988490/113681842-c5209200-96c2-11eb-9133-bf5c6f8d2bec.png)

Which is the error I got when running `rcall: install.packages('broom')` without specifying a repository (after, I did specify the repository and that installed successfully)

**Comment by NickCH-K** [comment]
Oh whoops, sorry that's my mistake in the post above. No matter how many times I do it I never remember that `rcall: install.packages()` doesn't have a default repo like when you run it in R directly.

**Comment by Danferno** [comment]
No problem

**Comment by NickCH-K** [comment]
Fixed with f4e2467
